### ISSUE TITLE
No callbacks?

### ISSUE THREAD

**Issue by KenWa51** [PrismarineJS/mineflayer-navigate#37]
Without callbacks this is very limited in it's use.

**Comment by KenWa51** [comment]
Just noticed there was one in .walk but It would be nice if there was one on .navigate so I didnt have to create my own function.

**Comment by rom1504** [comment]
There are events. You're authorised to read the example

**Comment by KenWa51** [comment]
Is there a way I could add an option where it'd be like flee(position to run from) or something like that?

**Comment by rom1504** [comment]
I don't think it really belong in that package.
You can code it in your bot.
Just pick a random position from that position using bot.blockAt and try go there

**Comment by KenWa51** [comment]
thats not very reliable though

**Comment by rom1504** [comment]
this package is about going from A to B.
It does that well.

Fleeing from an entity is by definition not reliable, in some cases it might even be impossible.

You could make another mineflayer plugins for this, it could use mineflayer-navigate for movement.

The way I suggested is a simple way to implement it but of course you're free to do something better.

**Comment by KenWa51** [comment]
Could you help me come up with an idea? I want to take the player's position and the mobs position and go backwards away from it what do you think I could do?

**Comment by rom1504** [comment]
something like that : 
```js
function norm(v) {
  return Math.sqrt(v.x*v.x + v.y*v.y + v.z*v.z)
}
function fleePosition(botPosition, entityPosition, distanceToFlee = 20) {
  const fromBotToEntity = entityPosition.minus(botPosition)
  const directionVector = fromBotToEntity.scaled(-distanceToFlee/norm(fromBotToEntity))
  return botPosition.plus(directionVector)
}

const fleePosition = fleePosition(bot.entity.position, yourEntity)
bot.navigate.to(fleePosition)
bot.navigate.on('pathFound', function (path) {
  bot.chat("found path. I can get there in " + path.length + " moves.");
});
bot.navigate.on('cannotFind', function (closestPath) {
  bot.chat("unable to find path. getting as close as possible");
  bot.navigate.walk(closestPath);
});
bot.navigate.on('arrived', function () {
  bot.chat("I have arrived");
});
bot.navigate.on('interrupted', function() {
  bot.chat("stopping");
});
```

**Comment by KenWa51** [comment]
You should add that as an example if it works!

**Comment by rom1504** [comment]
It should work but you need to replace the "yourEntity" by the entity you want to flee from (you can use bot.entities to get it)
I didn't test it at all though, you can test it ;)

**Comment by KenWa51** [comment]
It worked! 😄

**Comment by KenWa51** [comment]
Also It'd be nice if the bot would be able to move on a chunk by chunk basis so if a coordinate is out of the bot's range of view it will slowly make its way there using its available chunks

**Comment by ImHarvol** [comment]
I found a callback in the [navigateTo](https://github.com/PrismarineJS/mineflayer-navigate/blob/master/index.js#L144) function:
`
bot.navigate.to(position, {onArrived () {
                        // Your callback
                    }})
`
