### ISSUE TITLE
now how can i make bot go to any block of certain type

### ISSUE THREAD

**Issue by MaxProg2** [PrismarineJS/mineflayer-navigate#43]
for example, make bot go chop 1 tree of wood

**Comment by rom1504** [comment]
Use block finder plugin to find a block and go there

**Comment by MaxProg2** [comment]
i have a question, when i install a plugin, do i have to do it in the mineflayer folder? i mean the main thinbg that makes all work, do i have to install it in that folder? or i just open the folder of the plugin and write npm install in terminal
