### ISSUE TITLE
TypeError: Cannot read property 'floored' of undefined

### ISSUE THREAD

**Issue by nano38** [PrismarineJS/mineflayer-navigate#45]
Here's my code:
`bot.navigate.to(vec3(0,0,0));`

I'm trying to make a navigation system to have it go to different positions in the world, but i keep getting this error and I don't know how to fix it.

**Comment by rom1504** [comment]
The error means you're making make the bot go to a block that doesn't exist.
Indeed 0,0,0 doesn't have any block.
