### ISSUE TITLE
bot glich in farmland

### ISSUE THREAD

**Issue by leopoldhub** [PrismarineJS/mineflayer-navigate#53]
Im testing to make a bot to farm wheat and use mineflayer-navigate to move the bot in the farm.
When the bot is on normal ground (dirt, stone...) all is fine, the bot move correctly. But when he goes on farmland, he glich and is unable to move... can you help me? 

im on vanilla server 1.12.2

here a gif of the bot gliching: https://imgur.com/a/3Yo7Vwd

**Comment by rom1504** [comment]
I advise you use mineflayer pathfinder

**Comment by leopoldhub** [comment]
yes i think
`bot.navigate.to(blocks[i].position);`

**Comment by rom1504** [comment]
https://github.com/Karang/mineflayer-pathfinder

**Comment by leopoldhub** [comment]
ok.... thx a lot ^^
