### ISSUE TITLE
Bot stops following user because it can't find them when they jump.

### ISSUE THREAD

**Issue by kaden-tech** [PrismarineJS/mineflayer-navigate#63]
I make it go to their pos in a loop.
When the player jumps the bot pauses to recalculate.
I can't get around this.

**Comment by ProDev76** [comment]
You might get support from someone else, However I suggest using [mineflayer-pathfinder](https://github.com/PrismarineJS/mineflayer-pathfinder). It uses A* Pathfinding and is More robust, This package is also deprecated meaning it won't be updated.

**Comment by kaden-tech** [comment]
Got it. Thanks.
